### ISSUE TITLE
Improve join-link hashing: now it contains workspace.id directly

### ISSUE THREAD

**Issue by neSpecc** [codex-team/hawk.api.nodejs#150]
For now any user can join any workspace if they know its id:

<img width="852" alt="image" src="https://user-images.githubusercontent.com/3684889/77186135-73bb5a00-6ae3-11ea-9ee1-8a07960ec6ef.png">

**Comment by neSpecc** [comment]
Ссылки для приглашений через почту и публичная ссылка для вступления должны отличаться

**Comment by neSpecc** [comment]
Ссылки должны содержать hash, который будет храниться в базе

**Comment by nikmel2803** [comment]
шаги для решения задачи
1) сделать функция для генерации уникального инвайт-хеша
2) при создании воркспейса генерировать этот инвайт хэш и сохранять его вместе с воркспейсом (добавить новое поле в WorkspaceDBScheme в hawk.types)
3) отдавать хэш через GraphQL API (добавить новое поле в type Workspace)
4) в гараже выводить ссылку с этим хэшом
5) пофиксить мутацию confirmInvitation. Нужно искать нужный воркспейс не по id, а по хэшу.

**Comment by ilyamore88** [comment]
Done
