### ISSUE TITLE
Написать API для получения списка тарифных планов

### ISSUE THREAD

**Issue by nikmel2803** [codex-team/hawk.api.nodejs#221]
Нужно API, которое вернёт список тарифных планов. Необходимые фабрики и модели уже есть

Нужно написать схему в GraphQL и резолверы.
Поля для схемы сделать как в модели

**Comment by gohabereg** [comment]
#224

**Comment by gohabereg** [comment]
codex-team/hawk.garage#311

**Comment by gohabereg** [comment]
Resolved by #224
