### ISSUE TITLE
Написать API для смены тарифного плана

### ISSUE THREAD

**Issue by nikmel2803** [codex-team/hawk.api.nodejs#222]
мутация должна принимать id нового плана
мутация должна возвращать обновлённый воркспейс (отдельный Payload тип с id воркспейса и самим воркспейсом)
пример: https://github.com/codex-team/codex-accounting/blob/master/src/typeDefs/depositMutations.ts

**Comment by gohabereg** [comment]
codex-team/hawk.garage#311
