### ISSUE TITLE
Remove dependency form Events DB

### ISSUE THREAD

**Issue by neSpecc** [codex-team/hawk.api.nodejs#331]
- Remove connection from the app bootstrap
- Create a singleton
- Try to connect on the first request
- Use [exponential backoff](https://en.wikipedia.org/wiki/Exponential_backoff) scheme for reconnection
- Test how it works when Events DB is down — it should work fine. Garage should work fine — events list will be empty, but other staff should be hydrated

**Comment by ilyamore88** [comment]
- If events database drops after API starting, API can't fetch events;
- API doesn't fall;
- It's waiting 10 seconds for DB answer, but it's getting `MongoServerSelectionError`:
![image](https://user-images.githubusercontent.com/37909603/123317096-49eab180-d536-11eb-9a9f-b75c1921dc18.png)

**Comment by neSpecc** [comment]
Unfinished. Requires design, and  reconnection logic
